import type { components, operations } from "../models/custody-types.js"
import type { Prettify, RequiredExceptFor } from "../type-utils/index.js"

// Intent status
export type Core_IntentStatus = components["schemas"]["Core_IntentStatus"]

/** Terminal statuses that indicate the intent has finished processing */
export const TERMINAL_STATUSES: Core_IntentStatus[] = ["Executed", "Failed", "Expired", "Rejected"]

/** Statuses that indicate the intent is still pending or in progress */
export const PENDING_STATUSES: Core_IntentStatus[] = ["Open", "Approved", "Executing"]

/**
 * Options for waiting for intent execution
 */
export type WaitForExecutionOptions = {
  /**
   * Maximum number of polling attempts (default: 10). Also bounds how long a
   * not-yet-available (404) intent is waited for, since 404s are retried within
   * the same loop.
   */
  maxRetries?: number
  /** Interval between polling attempts in milliseconds (default: 3000) */
  intervalMs?: number
  /**
   * Callback function called on each status check.
   * Useful for logging or updating UI.
   */
  onStatusCheck?: (status: Core_IntentStatus, attempt: number) => void
}

/**
 * Result of waiting for intent execution
 */
export type WaitForExecutionResult = {
  /** The final status of the intent */
  status: Core_IntentStatus
  /** Whether the intent reached a terminal status */
  isTerminal: boolean
  /** Whether the intent was successfully executed */
  isSuccess: boolean
  /** The full intent object */
  intent: Core_TrustedIntent
  /**
   * Why the wait did not succeed, in one sentence — `undefined` exactly when
   * `isSuccess` is true. Set on non-terminal outcomes too: an intent still
   * `Open` when the attempts ran out is waiting on a human approval, which is
   * the most confusing outcome to be left without an explanation.
   *
   * A message, not a contract — the wording will change. Narrow on `status`
   * and read `intent.data.state.error` for anything the code has to branch on.
   */
  reason?: string
}

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_ApproveIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_ApproveIntentBody"], "signature">
>

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_ProposeIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_ProposeIntentBody"], "signature">
>

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_RejectIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_RejectIntentBody"], "signature">
>

export type Core_IntentResponse = components["schemas"]["Core_IntentResponse"]

/** The `v0_*` payload an intent proposes. */
export type Core_ProposeUserIntentPayload = components["schemas"]["Core_ProposeUserIntentPayload"]

/**
 * The envelope fields every intent request carries, whatever its payload.
 *
 * `XrplIntentOptions` extends this with the transaction-order specifics
 * (`ledgerId`, `feePriority`, `payloadId`, `payloadCustomProperties`), which
 * mean nothing to the other 40-odd payload types.
 */
export type IntentEnvelopeOptions = {
  /**
   * Domain to propose the intent in. Required when the login has more than one
   * domain; otherwise the single domain is used.
   */
  domainId?: string
  /** Number of days until the intent expires. Defaults to 1. */
  expiryDays?: number
  /** Human-readable description for the intent request (`request.description`). */
  description?: string
  /** Custom properties to include in the intent request. */
  requestCustomProperties?: Record<string, string>
  /**
   * Request id to propose under. Defaults to a fresh UUID v7, which is returned
   * either way — this is the id the intent is polled and approved by.
   */
  requestId?: string
}

/**
 * Outcome of proposing a payload: the request id the SDK proposed it under, and
 * the domain it resolved.
 *
 * `domainId` is returned because every follow-up is domain-scoped — without it
 * the `requestId` is an id the caller cannot look up.
 */
export type ProposePayloadResult = Prettify<Core_IntentResponse & { domainId: string }>

/**
 * Options for `intents.proposeAndWait` — the envelope fields, plus how long to
 * poll.
 *
 * Flat rather than per-stage bags (as `xrpl.proposeIntentAndWait` uses), because
 * there is only one wait here: custody accepting the intent.
 */
export type ProposePayloadAndWaitOptions = Prettify<IntentEnvelopeOptions & WaitForExecutionOptions>

/**
 * Outcome of proposing a payload and waiting it out.
 *
 * The top level is exactly {@link WaitForExecutionResult}, so anything written
 * against `intents.getAndWait` reads the same here, with the ids the propose
 * step resolved added alongside.
 */
export type ProposePayloadAndWaitResult = Prettify<
  WaitForExecutionResult & {
    /** The intent request id, as `proposePayload` returns it */
    requestId: string
    /** The domain the intent was proposed in */
    domainId: string
  }
>

// Get intent
export type Core_GetIntentPathParams = operations["getIntent"]["parameters"]["path"]
export type Core_TrustedIntent = components["schemas"]["Core_TrustedIntent"]

// Get intents
export type Core_GetIntentsPathParams = operations["getIntents"]["parameters"]["path"]
export type Core_GetIntentsQueryParams = operations["getIntents"]["parameters"]["query"]

// Dry run intent
export type Core_IntentDryRunRequest = components["schemas"]["Core_IntentDryRunRequest"]
export type Core_IntentDryRunResponse = components["schemas"]["Core_IntentDryRunResponse"]

// Remaining users for an intent
export type Core_RemainingUsersIntentPathParams =
  operations["getRemainingUsers"]["parameters"]["path"]
export type Core_RemainingUsersIntentQueryParams =
  operations["getRemainingUsers"]["parameters"]["query"]
export type Core_RemainingDomainUsers = components["schemas"]["Core_RemainingDomainUsers"]
