// @ts-check
/**
 * Derive the per-version **capability data** the runtime guard consults offline
 * (for an explicit `apiVersion`). For each bundled document this records, keyed
 * by `x-app-version`:
 *
 * - `endpoints` — every `METHOD /path` the version serves;
 * - `schemas`   — every component schema name the version defines (this is how
 *   feature capabilities such as `Core_XrplOperation_Batch` are detected).
 *
 * The runtime source of truth is still the live instance spec; this bundled
 * data is the offline / explicit-version fallback.
 */

/** OpenAPI path-item keys that denote an operation. */
const HTTP_METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"]

/**
 * @param {any} doc
 * @returns {{ version: string, endpoints: string[], schemas: string[] }}
 */
export function extractCapabilities(doc) {
  const version = doc?.info?.["x-app-version"] ?? "unknown"

  const endpoints = []
  for (const [path, item] of Object.entries(doc?.paths ?? {})) {
    if (item === null || typeof item !== "object") continue
    for (const method of HTTP_METHODS) {
      if (item[method]) endpoints.push(`${method.toUpperCase()} ${path}`)
    }
  }

  const schemas = Object.keys(doc?.components?.schemas ?? {})

  return {
    version,
    endpoints: endpoints.sort(),
    schemas: schemas.sort(),
  }
}

/**
 * Build the offline capability dataset from the **official** specs only
 * (ADR-0005): devbox specs contribute to the superset types but not to the
 * per-version dataset that backs `apiVersion`.
 *
 * An official release serves both its public and its internal surface
 * (ADR-0007), so the two specs of one release **union** into a single version
 * entry — an `apiVersion` pin gates internal endpoints exactly like public
 * ones. Within a surface, official releases have unique `x-app-version`
 * strings, so a duplicate there is a collision we refuse to resolve silently.
 *
 * Each entry records the `surfaces` that contributed to it, so the runtime
 * guard can tell "this release does not serve that endpoint" from "no spec for
 * that surface was ever bundled" — the latter fails open instead of rejecting
 * every internal call.
 *
 * @param {Array<{ doc: any, surface?: string }>} taggedDocs - official OpenAPI
 *   documents tagged with their surface (`surface` defaults to `"public"`).
 * @returns {Record<string, { surfaces: string[], endpoints: string[], schemas: string[] }>}
 */
export function buildCapabilityDataset(taggedDocs) {
  /** @type {Record<string, { surfaces: string[], endpoints: string[], schemas: string[] }>} */
  const dataset = {}
  /** @type {Set<string>} */
  const seen = new Set()

  for (const { doc, surface = "public" } of taggedDocs) {
    const { version, endpoints, schemas } = extractCapabilities(doc)

    const key = `${surface} ${version}`
    if (seen.has(key)) {
      throw new Error(
        `Duplicate app version "${version}" in the capability dataset — two ` +
          `official ${surface} specs report the same x-app-version.`,
      )
    }
    seen.add(key)

    const entry = dataset[version] ?? { surfaces: [], endpoints: [], schemas: [] }
    dataset[version] = {
      surfaces: [...new Set([...entry.surfaces, surface])].sort(),
      endpoints: [...new Set([...entry.endpoints, ...endpoints])].sort(),
      schemas: [...new Set([...entry.schemas, ...schemas])].sort(),
    }
  }

  return dataset
}

/**
 * Render the generated `capabilities.generated.ts` module source.
 * @param {Record<string, { surfaces: string[], endpoints: string[], schemas: string[] }>} dataset
 * @returns {string}
 */
export function renderCapabilitiesModule(dataset) {
  const versions = Object.keys(dataset).sort()

  const body = versions
    .map((version) => {
      const { surfaces, endpoints, schemas } = dataset[version]
      const surfaceList = surfaces.map((s) => JSON.stringify(s)).join(", ")
      const endpointList = endpoints.map((e) => `      ${JSON.stringify(e)},`).join("\n")
      const schemaList = schemas.map((s) => `      ${JSON.stringify(s)},`).join("\n")
      return [
        `  ${JSON.stringify(version)}: {`,
        `    surfaces: [${surfaceList}],`,
        `    endpoints: [`,
        endpointList,
        `    ],`,
        `    schemas: [`,
        schemaList,
        `    ],`,
        `  },`,
      ].join("\n")
    })
    .join("\n")

  const versionUnion = versions.map((version) => `  | ${JSON.stringify(version)}`).join("\n")

  return `/**
 * This file was auto-generated by scripts/generate-custody-types.
 * Do not make direct changes to the file.
 *
 * Per-version capability data (offline / explicit-apiVersion fallback for the
 * runtime version guard). The live instance spec remains the source of truth.
 */

export type KnownAppVersion =
${versionUnion}

type CapabilityEntry = {
  surfaces: readonly ("public" | "internal")[]
  endpoints: readonly string[]
  schemas: readonly string[]
}

/**
 * Annotated rather than inferred from \`as const\`: the literal type of this
 * object is far too large for TypeScript to serialize into the declaration
 * file (TS7056). Consumers only ever feed the arrays into \`new Set(...)\`, so
 * the element literals buy nothing — only the version keys need to stay exact,
 * and \`KnownAppVersion\` above pins those.
 */
export const CAPABILITIES: Record<KnownAppVersion, CapabilityEntry> = {
${body}
}
`
}
