// @ts-check
/**
 * Derive the per-version **capability data** the runtime guard consults offline
 * (for an explicit `apiVersion`). For each bundled document this records, keyed
 * by `x-app-version`:
 *
 * - `endpoints` — every `METHOD /path` the version serves;
 * - `schemas`   — every component schema name the version defines (this is how
 *   feature capabilities such as `Core_XrplOperation_Batch` are detected).
 *
 * The runtime source of truth is still the live instance spec; this bundled
 * data is the offline / explicit-version fallback.
 */

/** OpenAPI path-item keys that denote an operation. */
const HTTP_METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"]

/**
 * @param {any} doc
 * @returns {{ version: string, endpoints: string[], schemas: string[] }}
 */
export function extractCapabilities(doc) {
  const version = doc?.info?.["x-app-version"] ?? "unknown"

  const endpoints = []
  for (const [path, item] of Object.entries(doc?.paths ?? {})) {
    if (item === null || typeof item !== "object") continue
    for (const method of HTTP_METHODS) {
      if (item[method]) endpoints.push(`${method.toUpperCase()} ${path}`)
    }
  }

  const schemas = Object.keys(doc?.components?.schemas ?? {})

  return {
    version,
    endpoints: endpoints.sort(),
    schemas: schemas.sort(),
  }
}

/**
 * Build the offline capability dataset from the **official** specs only
 * (ADR-0005): devbox specs contribute to the superset types but not to the
 * per-version dataset that backs `apiVersion`. Official releases have unique
 * `x-app-version` strings, so a duplicate version is a collision we refuse to
 * resolve silently.
 *
 * @param {any[]} docs - official OpenAPI documents
 * @returns {Record<string, { endpoints: string[], schemas: string[] }>}
 */
export function buildCapabilityDataset(docs) {
  /** @type {Record<string, { endpoints: string[], schemas: string[] }>} */
  const dataset = {}
  for (const doc of docs) {
    const { version, endpoints, schemas } = extractCapabilities(doc)
    if (version in dataset) {
      throw new Error(
        `Duplicate app version "${version}" in the capability dataset — two ` +
          `official specs report the same x-app-version.`,
      )
    }
    dataset[version] = { endpoints, schemas }
  }
  return dataset
}

/**
 * Render the generated `capabilities.generated.ts` module source.
 * @param {Record<string, { endpoints: string[], schemas: string[] }>} dataset
 * @returns {string}
 */
export function renderCapabilitiesModule(dataset) {
  const versions = Object.keys(dataset).sort()

  const body = versions
    .map((version) => {
      const { endpoints, schemas } = dataset[version]
      const endpointList = endpoints.map((e) => `      ${JSON.stringify(e)},`).join("\n")
      const schemaList = schemas.map((s) => `      ${JSON.stringify(s)},`).join("\n")
      return [
        `  ${JSON.stringify(version)}: {`,
        `    endpoints: [`,
        endpointList,
        `    ],`,
        `    schemas: [`,
        schemaList,
        `    ],`,
        `  },`,
      ].join("\n")
    })
    .join("\n")

  return `/**
 * This file was auto-generated by scripts/generate-custody-types.
 * Do not make direct changes to the file.
 *
 * Per-version capability data (offline / explicit-apiVersion fallback for the
 * runtime version guard). The live instance spec remains the source of truth.
 */

export const CAPABILITIES = {
${body}
} as const

export type KnownAppVersion = keyof typeof CAPABILITIES
`
}
