// @ts-check
/**
 * Generate the SDK's type layer from every bundled OpenAPI spec in `openapi/`.
 *
 * Outputs:
 *   1. src/models/custody-types.ts        — the superset type universe for the
 *      **public** API, merged from all bundled public specs (the SDK compiles
 *      against this).
 *   2. src/models/custody-internal-types.ts — the same for the **internal** API
 *      (ADR-0007); written only when internal specs are bundled.
 *   3. src/models/capabilities.generated.ts — per-version capability data for
 *      the runtime version guard's offline / explicit-apiVersion fallback.
 *
 * This is a build-time script (never shipped): it lives outside `src/`, reads
 * files and calls openapi-typescript, delegating all decisions to the pure,
 * unit-tested helpers in this directory.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import openapiTS, { astToString } from "openapi-typescript"
import { buildCapabilityDataset, renderCapabilitiesModule } from "./capabilities.mjs"
import { INTERNAL_SURFACE, mergeOpenApiDocsBySurface, PUBLIC_SURFACE } from "./merge.mjs"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..")
const openapiDir = join(repoRoot, "openapi")
const modelsDir = join(repoRoot, "src", "models")

/** Generated types file per surface (ADR-0007). */
const TYPES_FILE = {
  [PUBLIC_SURFACE]: "custody-types.ts",
  [INTERNAL_SURFACE]: "custody-internal-types.ts",
}

/** @param {string} surface */
function typesHeader(surface) {
  return `/**
 * This file was auto-generated by scripts/generate-custody-types from the
 * merged superset of every ${surface} spec in openapi/. Do not make direct changes.
 */

`
}

/**
 * Load every bundled spec, tagged with its **channel** and its **surface**:
 *
 * - **channel** — the `openapi/<channel>/` folder it lives in (`official`,
 *   `devbox`, …). Specs must live in a channel folder; a `.json` directly under
 *   `openapi/` is a build error (ADR-0005).
 * - **surface** — `internal` for specs under `openapi/<channel>/internal/`,
 *   `public` for specs at the channel root. `internal` is the only nested
 *   folder a channel may contain; anything else is a build error, so a typo
 *   can't silently drop specs from generation (ADR-0007).
 */
function loadDocs() {
  const entries = readdirSync(openapiDir, { withFileTypes: true })

  const stray = entries.filter((e) => e.isFile() && e.name.endsWith(".json")).map((e) => e.name)
  if (stray.length > 0) {
    throw new Error(
      `OpenAPI specs must live in a channel subfolder (e.g. openapi/official/, ` +
        `openapi/devbox/). Found stray spec(s) directly in openapi/: ${stray.join(", ")}`,
    )
  }

  const channels = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()

  const docs = []
  for (const channel of channels) {
    const channelDir = join(openapiDir, channel)
    const channelEntries = readdirSync(channelDir, { withFileTypes: true })

    const unknownDirs = channelEntries
      .filter((e) => e.isDirectory() && e.name !== INTERNAL_SURFACE)
      .map((e) => e.name)
    if (unknownDirs.length > 0) {
      throw new Error(
        `A channel folder may only contain specs and an "${INTERNAL_SURFACE}/" ` +
          `subfolder. Found in openapi/${channel}/: ${unknownDirs.join(", ")}`,
      )
    }

    const sources = [
      { surface: PUBLIC_SURFACE, dir: channelDir, prefix: `${channel}/` },
      {
        surface: INTERNAL_SURFACE,
        dir: join(channelDir, INTERNAL_SURFACE),
        prefix: `${channel}/${INTERNAL_SURFACE}/`,
        optional: true,
      },
    ]

    for (const { surface, dir, prefix, optional } of sources) {
      if (optional && !channelEntries.some((e) => e.isDirectory() && e.name === INTERNAL_SURFACE)) {
        continue
      }
      const files = readdirSync(dir)
        .filter((f) => f.endsWith(".json"))
        .sort()
      for (const file of files) {
        const doc = JSON.parse(readFileSync(join(dir, file), "utf8"))
        docs.push({
          file: `${prefix}${file}`,
          channel,
          surface,
          version: doc?.info?.["x-app-version"] ?? "(unknown)",
          doc,
        })
      }
    }
  }

  if (docs.length === 0) throw new Error(`No OpenAPI specs found in ${openapiDir}`)
  return docs
}

async function main() {
  const docs = loadDocs()
  console.log(`Found ${docs.length} bundled spec(s):`)
  for (const { file, channel, surface, version } of docs) {
    console.log(`  - ${file}  (${channel}/${surface}, x-app-version ${version})`)
  }

  // Superset types are merged from every channel (devbox features stay typed),
  // one document per surface (ADR-0007).
  const bySurface = mergeOpenApiDocsBySurface(
    docs.map((d) => ({ doc: d.doc, channel: d.channel, surface: d.surface })),
  )

  const written = []
  for (const [surface, { merged, warnings }] of Object.entries(bySurface)) {
    for (const w of warnings) console.warn(`  ⚠ [${surface}] ${w}`)
    console.log(
      `Superset (${surface}): ${Object.keys(merged.paths).length} paths, ` +
        `${Object.keys(merged.components?.schemas ?? {}).length} schemas` +
        (warnings.length ? `, ${warnings.length} divergence warning(s)` : ""),
    )

    const ast = await openapiTS(merged)
    writeFileSync(join(modelsDir, TYPES_FILE[surface]), typesHeader(surface) + astToString(ast))
    written.push(TYPES_FILE[surface])
  }

  // The offline capability dataset (and thus apiVersion) is official-only, but
  // spans both surfaces of each official release.
  const officialDocs = docs
    .filter((d) => d.channel === "official")
    .map((d) => ({ doc: d.doc, surface: d.surface }))
  const dataset = buildCapabilityDataset(officialDocs)
  writeFileSync(join(modelsDir, "capabilities.generated.ts"), renderCapabilitiesModule(dataset))
  written.push("capabilities.generated.ts")

  console.log(`Wrote ${written.map((f) => `src/models/${f}`).join(", ")}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
