// @ts-check
/**
 * Generate the SDK's type layer from every bundled OpenAPI spec in `openapi/`.
 *
 * Outputs two artifacts:
 *   1. src/models/custody-types.ts        — one superset type universe merged
 *      from all bundled specs (the SDK compiles against this).
 *   2. src/models/capabilities.generated.ts — per-version capability data for
 *      the runtime version guard's offline / explicit-apiVersion fallback.
 *
 * This is a build-time script (never shipped): it lives outside `src/`, reads
 * files and calls openapi-typescript, delegating all decisions to the pure,
 * unit-tested helpers in this directory.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import openapiTS, { astToString } from "openapi-typescript"
import { buildCapabilityDataset, renderCapabilitiesModule } from "./capabilities.mjs"
import { mergeOpenApiDocs } from "./merge.mjs"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..")
const openapiDir = join(repoRoot, "openapi")
const modelsDir = join(repoRoot, "src", "models")

const TYPES_HEADER = `/**
 * This file was auto-generated by scripts/generate-custody-types from the
 * merged superset of every spec in openapi/. Do not make direct changes.
 */

`

/**
 * Load every bundled spec, tagged with its **channel** — the `openapi/<channel>/`
 * subfolder it lives in (`official`, `devbox`, …). Specs must live in a channel
 * subfolder; a `.json` directly under `openapi/` is a build error (ADR-0005).
 */
function loadDocs() {
  const entries = readdirSync(openapiDir, { withFileTypes: true })

  const stray = entries.filter((e) => e.isFile() && e.name.endsWith(".json")).map((e) => e.name)
  if (stray.length > 0) {
    throw new Error(
      `OpenAPI specs must live in a channel subfolder (e.g. openapi/official/, ` +
        `openapi/devbox/). Found stray spec(s) directly in openapi/: ${stray.join(", ")}`,
    )
  }

  const channels = entries
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()

  const docs = []
  for (const channel of channels) {
    const channelDir = join(openapiDir, channel)
    const files = readdirSync(channelDir)
      .filter((f) => f.endsWith(".json"))
      .sort()
    for (const file of files) {
      const doc = JSON.parse(readFileSync(join(channelDir, file), "utf8"))
      docs.push({
        file: `${channel}/${file}`,
        channel,
        version: doc?.info?.["x-app-version"] ?? "(unknown)",
        doc,
      })
    }
  }

  if (docs.length === 0) throw new Error(`No OpenAPI specs found in ${openapiDir}`)
  return docs
}

async function main() {
  const docs = loadDocs()
  console.log(`Found ${docs.length} bundled spec(s):`)
  for (const { file, channel, version } of docs) {
    console.log(`  - ${file}  (${channel}, x-app-version ${version})`)
  }

  // Superset types are merged from every channel (devbox features stay typed).
  const { merged, warnings } = mergeOpenApiDocs(
    docs.map((d) => ({ doc: d.doc, channel: d.channel })),
  )
  for (const w of warnings) console.warn(`  ⚠ ${w}`)
  console.log(
    `Superset: ${Object.keys(merged.paths).length} paths, ` +
      `${Object.keys(merged.components?.schemas ?? {}).length} schemas` +
      (warnings.length ? `, ${warnings.length} divergence warning(s)` : ""),
  )

  const ast = await openapiTS(merged)
  writeFileSync(join(modelsDir, "custody-types.ts"), TYPES_HEADER + astToString(ast))

  // The offline capability dataset (and thus apiVersion) is official-only.
  const officialDocs = docs.filter((d) => d.channel === "official").map((d) => d.doc)
  const dataset = buildCapabilityDataset(officialDocs)
  writeFileSync(join(modelsDir, "capabilities.generated.ts"), renderCapabilitiesModule(dataset))

  console.log("Wrote src/models/custody-types.ts and src/models/capabilities.generated.ts")
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
