// @ts-check
/**
 * Generate the SDK's type layer from every bundled OpenAPI spec in `openapi/`.
 *
 * Outputs two artifacts:
 *   1. src/models/custody-types.ts        — one superset type universe merged
 *      from all bundled specs (the SDK compiles against this).
 *   2. src/models/capabilities.generated.ts — per-version capability data for
 *      the runtime version guard's offline / explicit-apiVersion fallback.
 *
 * This is a build-time script (never shipped): it lives outside `src/`, reads
 * files and calls openapi-typescript, delegating all decisions to the pure,
 * unit-tested helpers in this directory.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import openapiTS, { astToString } from "openapi-typescript"
import { buildCapabilityDataset, renderCapabilitiesModule } from "./capabilities.mjs"
import { mergeOpenApiDocs } from "./merge.mjs"

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, "..", "..")
const openapiDir = join(repoRoot, "openapi")
const modelsDir = join(repoRoot, "src", "models")

const TYPES_HEADER = `/**
 * This file was auto-generated by scripts/generate-custody-types from the
 * merged superset of every spec in openapi/. Do not make direct changes.
 */

`

function loadDocs() {
  const files = readdirSync(openapiDir)
    .filter((f) => f.endsWith(".json"))
    .sort()
  if (files.length === 0) throw new Error(`No OpenAPI specs found in ${openapiDir}`)
  return files.map((file) => {
    const doc = JSON.parse(readFileSync(join(openapiDir, file), "utf8"))
    return { file, version: doc?.info?.["x-app-version"] ?? "(unknown)", doc }
  })
}

async function main() {
  const docs = loadDocs()
  console.log(`Found ${docs.length} bundled spec(s):`)
  for (const { file, version } of docs) console.log(`  - ${file}  (x-app-version ${version})`)

  const { merged, warnings } = mergeOpenApiDocs(docs.map((d) => d.doc))
  for (const w of warnings) console.warn(`  ⚠ ${w}`)
  console.log(
    `Superset: ${Object.keys(merged.paths).length} paths, ` +
      `${Object.keys(merged.components?.schemas ?? {}).length} schemas` +
      (warnings.length ? `, ${warnings.length} divergence warning(s)` : ""),
  )

  const ast = await openapiTS(merged)
  writeFileSync(join(modelsDir, "custody-types.ts"), TYPES_HEADER + astToString(ast))

  const dataset = buildCapabilityDataset(docs.map((d) => d.doc))
  writeFileSync(join(modelsDir, "capabilities.generated.ts"), renderCapabilitiesModule(dataset))

  console.log("Wrote src/models/custody-types.ts and src/models/capabilities.generated.ts")
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
