import type { components } from "../../models/custody-types.js"
import type { RequiredExceptFor } from "../../type-utils/index.js"

// If signature is not provided, it will be generated by the SDK
export type Core_ApproveIntentBody = RequiredExceptFor<
  components["schemas"]["Core_ApproveIntentBody"],
  "signature"
>

// If signature is not provided, it will be generated by the SDK
export type Core_ProposeIntentBody = RequiredExceptFor<
  components["schemas"]["Core_ProposeIntentBody"],
  "signature"
>

// If signature is not provided, it will be generated by the SDK
export type Core_RejectIntentBody = RequiredExceptFor<
  components["schemas"]["Core_RejectIntentBody"],
  "signature"
>

export type Core_IntentResponse = components["schemas"]["Core_IntentResponse"]
