import type { components, operations } from "../../models/custody-types.js"
import type { Prettify, RequiredExceptFor } from "../../type-utils/index.js"

// Intent status
export type Core_IntentStatus = components["schemas"]["Core_IntentStatus"]

/** Terminal statuses that indicate the intent has finished processing */
export const TERMINAL_STATUSES: Core_IntentStatus[] = ["Executed", "Failed", "Expired", "Rejected"]

/** Statuses that indicate the intent is still pending or in progress */
export const PENDING_STATUSES: Core_IntentStatus[] = ["Open", "Approved", "Executing"]

/**
 * Options for waiting for intent execution
 */
export type WaitForExecutionOptions = {
  /** Maximum number of polling attempts (default: 10) */
  maxRetries?: number
  /** Interval between polling attempts in milliseconds (default: 3000) */
  intervalMs?: number
  /**
   * Maximum number of retries when the intent is not found (404).
   * Useful when calling immediately after proposeIntent. (default: 3)
   */
  notFoundRetries?: number
  /**
   * Interval between retries when the intent is not found in milliseconds (default: 1000)
   */
  notFoundIntervalMs?: number
  /**
   * Callback function called on each status check.
   * Useful for logging or updating UI.
   */
  onStatusCheck?: (status: Core_IntentStatus, attempt: number) => void
}

/**
 * Result of waiting for intent execution
 */
export type WaitForExecutionResult = {
  /** The final status of the intent */
  status: Core_IntentStatus
  /** Whether the intent reached a terminal status */
  isTerminal: boolean
  /** Whether the intent was successfully executed */
  isSuccess: boolean
  /** The full intent object */
  intent: Core_TrustedIntent
}

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_ApproveIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_ApproveIntentBody"], "signature">
>

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_ProposeIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_ProposeIntentBody"], "signature">
>

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_RejectIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_RejectIntentBody"], "signature">
>

export type Core_IntentResponse = components["schemas"]["Core_IntentResponse"]

// Get intent - make domainId optional for better DX
export type Core_GetIntentPathParams = Prettify<
  RequiredExceptFor<operations["getIntent"]["parameters"]["path"], "domainId">
>
export type Core_TrustedIntent = components["schemas"]["Core_TrustedIntent"]

// Get intents - make domainId optional for better DX
export type Core_GetIntentsPathParams = Prettify<
  RequiredExceptFor<operations["getIntents"]["parameters"]["path"], "domainId">
>
export type Core_GetIntentsQueryParams = operations["getIntents"]["parameters"]["query"]

// Dry run intent
export type Core_IntentDryRunRequest = components["schemas"]["Core_IntentDryRunRequest"]
export type Core_IntentDryRunResponse = components["schemas"]["Core_IntentDryRunResponse"]

// Remaining users for an intent - make domainId optional for better DX
export type Core_RemainingUsersIntentPathParams = Prettify<
  RequiredExceptFor<operations["getRemainingUsers"]["parameters"]["path"], "domainId">
>
export type Core_RemainingUsersIntentQueryParams =
  operations["getRemainingUsers"]["parameters"]["query"]
export type Core_RemainingDomainUsers = components["schemas"]["Core_RemainingDomainUsers"]
