import type { components, operations } from "../../models/custody-types.js"
import type { Prettify, RequiredExceptFor } from "../../type-utils/index.js"

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_ApproveIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_ApproveIntentBody"], "signature">
>

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_ProposeIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_ProposeIntentBody"], "signature">
>

/**
 * Signature is optional, if not provided, it will be generated by the SDK
 */
export type Core_RejectIntentBody = Prettify<
  RequiredExceptFor<components["schemas"]["Core_RejectIntentBody"], "signature">
>

export type Core_IntentResponse = components["schemas"]["Core_IntentResponse"]

// Get intent
export type Core_GetIntentPathParams = operations["getIntent"]["parameters"]["path"]
export type Core_TrustedIntent = components["schemas"]["Core_TrustedIntent"]

// Get intents
export type Core_GetIntentsPathParams = operations["getIntents"]["parameters"]["path"]
export type Core_GetIntentsQueryParams = operations["getIntents"]["parameters"]["query"]

// Dry run intent
export type Core_IntentDryRunRequest = components["schemas"]["Core_IntentDryRunRequest"]
export type Core_IntentDryRunResponse = components["schemas"]["Core_IntentDryRunResponse"]

// Remaining users for an intent
export type Core_RemainingUsersIntentPathParams =
  operations["getRemainingUsers"]["parameters"]["path"]
export type Core_RemainingUsersIntentQueryParams =
  operations["getRemainingUsers"]["parameters"]["query"]
export type Core_RemainingDomainUsers = components["schemas"]["Core_RemainingDomainUsers"]
